const mongoose=require('mongoose');
const ProductSchema=mongoose.Schema({
   name:{
        type:String,
        required:true
    },
    quantity:{
        type:Number,
        required:true,
        default:0
    },
    price:{
        type:Number,
        required:true,
        default:0
    },
    description:{
        type:String,
        required:false
    },
    image:{
        type:String,
        required:false
    },
    category:{
        type:String,
        required:false
    },
    stock:{
        type:Number,
        required:false
    }}
    ,
    {
        timestamps:true
    }
)
module.exports=mongoose.model('Product',ProductSchema)